<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TC_Task_OrangeHRM</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>5dda19b7-1222-4a2a-8797-b2f67d2320d9</testSuiteGuid>
   <testCaseLink>
      <guid>80bec996-a28c-46de-86d4-69f59cb89962</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Manual/TC_Task_OrangeHRM_Positive_1</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>496dfbf5-a9e7-4cdd-9c9a-91b55a0d8de3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b7b8be87-db8c-4675-b4c5-a8ff5ac91ea7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f6b7a200-a930-4013-9779-199902df069c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Manual/TC_Task_OrangeHRM_Positive_2</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7515029e-c756-4c0b-b19d-7795da33e535</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>df6f8556-21d6-4429-9bce-0635de932c20</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>60c22263-b5b1-4e8c-a9e3-3a2c1432e764</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d6afbc07-fd6c-4625-8917-495b3638e034</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Manual/TC_Task_OrangeHRM_Negative_1</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e45cf7c7-b57f-44f7-a4fc-8fa2580b6ddd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8b6e9d5e-0f30-424c-a9d0-536fa8c290de</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2beb1536-e94c-42cc-92c5-3d99f79bf3d5</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>49744961-90c4-45c6-a53c-1438aa15b3ad</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Manual/TC_Task_OrangeHRM_Negative_2</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c68b5d1c-cc63-48e6-8dd0-78d9785e2b22</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>48c8bb8f-16da-492c-92d7-39cb2a56d35d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0beb8e09-769c-4e12-8a63-787dbbe48e23</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>54743afa-5522-459d-ae40-80c891a4c74e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f5886422-6981-4156-b8f9-048ae4f33cc0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>de93b203-c1ec-4619-994f-c3bd0d58e57f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Manual/TC_Task_OrangeHRM_Negative_3</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e4878a35-2a84-411b-acc7-81eeaa2683f6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8ef4ebdd-4980-4d57-b1c9-c11d29b112e9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>00ec8c91-10fb-4bec-a158-05c54549ce8b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9a0cf4bb-9696-4b0c-ad6c-a9a8cb782e53</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
