<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>notif_add_success</name>
   <tag></tag>
   <elementGuidId>7c14c4dc-d716-437b-b6b2-fe9da47cdbb5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>.message</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>.message</value>
   </webElementProperties>
</WebElementEntity>
