<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>panel_admin</name>
   <tag></tag>
   <elementGuidId>291836fd-1874-4ea2-9486-fa037e55859e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//b[.='Admin']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//b[.='Admin']</value>
   </webElementProperties>
</WebElementEntity>
