<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>verify_add_employee_LName</name>
   <tag></tag>
   <elementGuidId>77fcf696-5bac-4a3d-a4b3-cbd1b19ed9f9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@id='personal_txtEmpLastName'][count(. | //*[@id = 'personal_txtEmpLastName' and @name = 'personal[txtEmpLastName]']) = count(//*[@id = 'personal_txtEmpLastName' and @name = 'personal[txtEmpLastName]'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>personal_txtEmpLastName</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>personal[txtEmpLastName]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@id='personal_txtEmpLastName']</value>
   </webElementProperties>
</WebElementEntity>
